### ISSUE TITLE
No new cases count ma złe przykładowe wyniki

### ISSUE THREAD

**Issue by badochov** [korona-science/homework-badochov#1]
Przykałdowe wyniki no new cases count 
```
no_new_cases_count(11, 2, 2020) -> 35
```
```
no_new_cases_count(3, 3) -> 57
```

są nie poprawne. Poprawne to 42 i 7. Podane wyniki działają dla prowincji a nie krajów

**Comment by RouNNdeL** [comment]
W treści jest błąd, sorka
